### PR TITLE
Kw time stamp

### PR DESCRIPTION
**Pull request by KeithRWalker**
# IMPORTANT!!!!!
* #### Moment.js is now a part of the dependencies on here so everyone is gonna need to do `npm install` in their console even for the review. Otherwise you'll get errors.
* #### If that doesn't work make sure to check the addComments.js file for an import `import moment from 'moment'`,<--Must be exactly like that no file path
    * if none of that works then you gotta do `npm install moment --save`, but It should work if you do the first step correctly, after merging.
* #### Also If you'd like to use timestamps for anything on this project you must use the import from above, and then there are a bunch of different methods for calling it on the moment.js site.

Timestamps are displaying properly. There is some styling stuff with the comments that are a little off with the themes feature, but I'm gonna tackle those when adding the clear/delete features.

### CODE REVIEW

**Comment by sarahjulesthorne** [comment]
Hey, I am struggling to do the git fetch thing. What are the steps for that again? And what is the name of the branch? I tried typing:  
`git fetch kw-timeStamp`  
And then:  
`git checkout kw-timeStamp`  
But it didn't work.  
Help?

**Comment by sarahjulesthorne** [comment]
OK, I got it to work. I don't think we should merge in until we make sure your stuff doesn't break my modal.  
Can you get that working first?  
I'd like to make sure we don't permanently break my functionality.  
My first thing I'd try would be wrapping your UL in a div with my color class.  
I don't see exactly why that would make a difference, but that's what I would start with.  
Other option is that Moment doesn't work with my modal, in which case we're screwed?

**Comment by sarahjulesthorne** [comment]
:+1

**Review by emilykdewitt — COMMENTED** [review]
👍

**Pull request merged**
